In [ ]:
import numpy as np
import pandas as pd

# Comparações e Indexação booleana



In [ ]:
# criação dos arrays 
x = np.array([[1, 2], [3, 4]])
y = np.array([1.5, 3.5])
print("x: \n", x)
print("y: \n", y)

x: 
 [[1 2]
 [3 4]]
y: 
 [1.5 3.5]


In [ ]:
#comparações ponto a ponto
print("Comparação de um array com um esalar (>): \n", x > 2)
print("Comparação de um array com um esalar (>=): \n", x >= 2)
print("Comparação de um array com um esalar (<): \n", x < 2)
print("Comparação de um array com um esalar (<=): \n", x <= 2)
print("Comparação entre arrays (==): \n", x == x)
print("Comparação entre arrays (>): \n", x > x)
print("Comparação entre arrays (>): \n", x > y) #broadcasting


Comparação de um array com um esalar (>): 
 [[False False]
 [ True  True]]
Comparação de um array com um esalar (>=): 
 [[False  True]
 [ True  True]]
Comparação de um array com um esalar (<): 
 [[ True False]
 [False False]]
Comparação de um array com um esalar (<=): 
 [[ True  True]
 [False False]]
Comparação entre arrays (==): 
 [[ True  True]
 [ True  True]]
Comparação entre arrays (>): 
 [[False False]
 [False False]]
Comparação entre arrays (>): 
 [[False False]
 [ True  True]]


## Indexação booleana


In [ ]:
# indexação booleana

x = np.array([[1, 3, 7], [4, 11, 21], [42, 8, 9]])
print("x: \n", x)

x: 
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]


In [ ]:
#indexação booleana: retornar o numero de elementos maiores que k
k = 10
cond = x > k
print("condição: \n", cond)
print(f"elementos maiores que {k}: ", len(x[cond]))

condição: 
 [[False False False]
 [False  True  True]
 [ True False False]]
elementos maiores que 10:  3


In [ ]:
#indeção booleana: extração de números pares
cond = x % 2 == 0 #numeros pares
print("condição: \n", cond)
print("numeros pares", x[cond])

condição: 
 [[False False False]
 [ True False False]
 [ True  True False]]
numeros pares [ 4 42  8]


In [ ]:
# indexacao boolena extracao de numeros impares
cond = x % 2 == 1 #numeros impares
print("condição: \n", cond)
print("numeros impares", x[cond])

condição: 
 [[ True  True  True]
 [False  True  True]
 [False False  True]]
numeros impares [ 1  3  7 11 21  9]


# Numpy

In [ ]:

x = np.array([[1, 3, 7], [4, 11, 21], [42, 8, 9]])
print("x: \n", x)

x: 
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]


In [ ]:
# reshape: transforma a matriz em um vetor coluna
# (3, 3) vira (9, 1): 3*3 = 9*1 = 9
print("transformação de em um vetor coluna: \n", x.reshape(1, 9))
print("transformação de em um vetor coluna: \n", x.reshape(9, 1))

transformação de em um vetor coluna: 
 [[ 1  3  7  4 11 21 42  8  9]]
transformação de em um vetor coluna: 
 [[ 1]
 [ 3]
 [ 7]
 [ 4]
 [11]
 [21]
 [42]
 [ 8]
 [ 9]]


In [ ]:
#transposição de coluna
print("x transposta: \n", x.T)

x transposta: 
 [[ 1  4 42]
 [ 3 11  8]
 [ 7 21  9]]


In [ ]:
# np.sum : soma em um dado eixo, axis = {0: linha, 1: coluna}
x = np.array([[1, 3, 7], [4, 11, 21], [42, 8, 9]])
print("x: \n", x)
print("soma te todos os elementos do x: \n", np.sum(x))
print("soma te todos os elementos das linhas x: \n", np.sum(x, axis=0))
print("soma te todos os elementos das colunas x: \n", np.sum(x, axis=1))

x: 
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]
soma te todos os elementos do x: 
 106
soma te todos os elementos das linhas x: 
 [47 22 37]
soma te todos os elementos das colunas x: 
 [11 36 59]


In [ ]:
#np.mean: mpeda em um dado eixo, axis = {0: linha, 1:coluna}
print("x: \n", x)
print("média de todos elementos de x: ", np.mean(x))
print("média de x ao longo das linhas: ", np.mean(x, axis=0))
print("média de x ao longo das colunas: ", np.mean(x, axis=1))
# np.median (retorna a mediana)

x: 
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]
média de todos elementos de x:  11.777777777777779
média de x ao longo das linhas:  [15.66666667  7.33333333 12.33333333]
média de x ao longo das colunas:  [ 3.66666667 12.         19.66666667]


In [ ]:
#np.where, identificacao dos indices de uma dada condicao é atendida. uso conjunto com indexao booleana.
cond = x % 2== 0 #numeros pares
print("condicao: \n", cond)
i, j = np.where(cond) #indices x[i,j] = x[cond]
print("indice i (linhas): ",  i )
print("indice j (colunas): ",  j )



condicao: 
 [[False False False]
 [ True False False]
 [ True  True False]]
indice i (linhas):  [1 2 2]
indice j (colunas):  [0 0 1]


In [ ]:
#indexacao booleana e slicing: selecionar linhas de x que possuem algum numero par
print("x: \n", x)
cond = x % 2== 0 #numeros pares
print("condicao: \n", cond)

#se houver alguma condico True na linha, a soma será > 0
i_row = np.where(np.sum(cond, axis=1))[0]
print("indice das linhas que possuem numeros pares: ", i_row)
print("linhas que possuem numeros pares: ", x[i_row])

x: 
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]
condicao: 
 [[False False False]
 [ True False False]
 [ True  True False]]
indice das linhas que possuem numeros pares:  [1 2]
linhas que possuem numeros pares:  [[ 4 11 21]
 [42  8  9]]


# Regressão Linear

### Erro quadrático: 
### y = f(x) = ax + b

In [ ]:
#regressão linear com numpy

import matplotlib.pyplot as plt


In [ ]:
#aff mto mal feito o igti , sem base , cruzes