# Operações elemento a elemento

### Soma:

Sobrecarga operador "+"


np.add


### Subtração:

Sobrecarga operador "-"


np.subtract


### Divisão:

Sobrecarga operador "/"


np.divide


### Multiplicação:

Sobrecarga operador "*"


np.multiply



## Multiplicação de matrizes

Python puro: A @ B


Numpy:


np.dot(a, B)

A.dot(B)

In [ ]:
import numpy as np


In [ ]:
# Funções aritmeticas

x = np.ones((2,2)) #uns
y = np.eye(2) # identidade
print("x: \n", x)
print("y: \n", y)

x: 
 [[1. 1.]
 [1. 1.]]
y: 
 [[1. 0.]
 [0. 1.]]


In [ ]:
#soma 

print("soma de dois arrays: \n ", x + y)
print("soma com float/int: \n ", x + 2) #broadcasting

soma de dois arrays: 
  [[2. 1.]
 [1. 2.]]
soma com float/int: 
  [[3. 3.]
 [3. 3.]]


In [ ]:
#subtracao
print("subtracao de dois arrays: \n", x - y)
print("subtracao com float/int: \n", x-2)

subtracao de dois arrays: 
 [[0. 1.]
 [1. 0.]]
subtracao com float/int: 
 [[-1. -1.]
 [-1. -1.]]


In [ ]:
#divisao
print("divisao de dois arrays: \n", x /y)
print("divisao com float/int: \n", x/2)

divisao de dois arrays: 
 [[ 1. inf]
 [inf  1.]]
divisao com float/int: 
 [[0.5 0.5]
 [0.5 0.5]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


In [ ]:
#multiplicacao
print("divisao de dois arrays: \n", x *y)
print("divisao com float/int: \n", x*2)

divisao de dois arrays: 
 [[1. 0.]
 [0. 1.]]
divisao com float/int: 
 [[2. 2.]
 [2. 2.]]


In [ ]:
#quando o broadcastgin nao funciona
#np.array([1, 2, 3]) + np.array([1, 2])

#pq o shape nao é igual funciona com 1
np.array([1, 2, 3]) + np.array([1])

array([2, 3, 4])

In [ ]:
#combinacao
print("combinacao de operacoes: \n", (x+y)/(x/2) )

combinacao de operacoes: 
 [[4. 2.]
 [2. 4.]]


In [ ]:
#multiplicacao matricial
print("multiplicacao matriciail (np.dot): \n:", np.dot(x,y))
print("multiplicacao matriciail (@): \n:", x @ y)
print("multiplicacao matriciail (.dot): \n:", x.dot(y))


multiplicacao matriciail (np.dot): 
: [[1. 1.]
 [1. 1.]]
multiplicacao matriciail (@): 
: [[1. 1.]
 [1. 1.]]
multiplicacao matriciail (.dot): 
: [[1. 1.]
 [1. 1.]]


In [ ]:
5 * np.ones((10,10))

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [ ]:
"""
Exemplo:

Solução de um sistema de equações:
a + 2*b=7
3*a = 2*b = -11
solução analítica: (a,b) = (-1, 4)
Matricialmente, este problema tem a seguinte forma:
AX = C, onde:
-X = [a,b]
-A = [[1,2], [3,-2]]
-C = [7, -11]
solução numérica: x = inv(A) @ C,
"""


#definicicao do problema
A = np.array([[1,2], [3,-2]])
C = np.array([[7], [-11]])
print("A: \n", A)
print("C: \n", C)



A: 
 [[ 1  2]
 [ 3 -2]]
C: 
 [[  7]
 [-11]]


In [ ]:
#solucao
x = np.dot(np.linalg.inv(A), C) #linalg faz diversas funcoes matematicas, um deles é o inv, inverte a matriz
#x=np.linalg.inv(A) @ C
print("(a,b):", x.ravel()) #ravel faz 

(a,b): [-1.  4.]
