# 2 aula interativa


# Numpy

In [ ]:
import numpy as np


In [ ]:
help(np.array)
# ou np.array?

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly c

In [ ]:
# criação de um array 1D [1, 2, 3]
l = [1, 2, 3]
x = np.array(l)
#x = np.array(l, dtype=int) força o array ter somente inteiro
print("x: ", x)
print("shape: ", x.shape)
type(x)

x:  [1 2 3]
shape:  (3,)


numpy.ndarray

In [ ]:
# criação de um array 2D [[1, 2], [3, 4]]
l = [[1, 2], [3, 4]]
x = np.array(l)
print("x: \n ", x)
print("shape: ", x.shape)

x: 
  [[1 2]
 [3 4]]
shape:  (2, 2)


In [ ]:
#array contendo apenas zeros
dim = (2,2) #tupla
x = np.zeros(dim)
print("x: \n ", x)
print("shape: ", x.shape)

x: 
  [[0. 0.]
 [0. 0.]]
shape:  (2, 2)


In [ ]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [ ]:
#array contendo apenas um
size = (5, 5) #tupla
x = np.ones(size)
print("x: \n ", x)
print("shape: ", x.shape)

x: 
  [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
shape:  (5, 5)


In [ ]:
np.ones?

In [ ]:
# criacao de valores dentro de um intervalo
# valores uniformes entre 5 e 15
x_min, x_max = 5, 15
x = np.linspace(start=x_min, stop=x_max, num = 6)
print("x: ", x)
print("shape: ", x.shape)

x:  [ 5.  7.  9. 11. 13. 15.]
shape:  (6,)


In [ ]:
np.linspace?

In [ ]:
#criacao de matriz identidade
n=4
x = np.eye(n)
print("x: ", x)
print("shape: ", x.shape)

x:  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
shape:  (4, 4)


In [ ]:
# criacao de valores aleatorios
# np.random.seed(10)
x = np.random.random(size=(2,3))
print("x: ", x)
print("shape: ", x.shape)

x:  [[0.86564457 0.94005532 0.26299129]
 [0.95974498 0.79791275 0.74094972]]
shape:  (2, 3)


In [ ]:
help(np.random.random)

Help on built-in function random:

random(...) method of numpy.random.mtrand.RandomState instance
    random(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0). Alias for
    `random_sample` to ease forward-porting to the new random API.

