# indexacao de arrays


In [ ]:
import numpy as np


In [ ]:
# os indice no python vao de 0 a n-1
# onde n é o tamanho da dimensao
x = np.linspace(start=10, stop=100, num=10)
print('x: ', x)
print("shape: ", x.shape)

x:  [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
shape:  (10,)


In [ ]:
# extracao de elementos
print('x: ', x)
print('primeiro elemento: ', x[0])
print('ultimo elemento: ', x[-1])

x:  [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
primeiro elemento:  10.0
ultimo elemento:  100.0


In [ ]:
#slicing = extracao de subarrays
print('x: ', x)
print('dois primeiros elementos: ', x[0:2])
print('dois primeiros elementos: ', x[:2])
print('dois ultimos elementos: ', x[-2:])

x:  [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
dois primeiros elementos:  [10. 20.]
dois primeiros elementos:  [10. 20.]
dois ultimos elementos:  [ 90. 100.]


In [ ]:
# slicing em array @D (matrizes)
x = x.reshape(2,5) # reshape de x para 2 linhas e 5 colunas
print("x: \n", x)

x: 
 [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]


In [ ]:
#extracao de elementos
print("primeira linha, segunda coluna: ", x[0, 1])
print("ultima linha, ultima coluna: ", x[-1, -1])
print("ultima linha, ultima coluna: ", x[1, 4])

primeira linha, segunda coluna:  20.0
ultima linha, ultima coluna:  100.0
ultima linha, ultima coluna:  100.0


In [ ]:
#slicing: extracao de subarrays
print("x: \n", x)
print("primeira linha inteira: ", x[0, :])
print("primeira linha, segunda a quarta coluna: ", x[0, 1:4])
print("ultima linha inteira: \n", x [: , [-1]])

x: 
 [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]
primeira linha inteira:  [10. 20. 30. 40. 50.]
primeira linha, segunda a quarta coluna:  [20. 30. 40.]
ultima linha inteira: 
 [[ 50.]
 [100.]]


In [ ]:
#atencao com compartilhamento de memoria em subarrays!!
x = np.array([1,2,3])
print("x antes: ", x)
y = x[:2]
y[0] = -100 #alterao do valor y altera o valor de x
print("x depois: ", x)

x antes:  [1 2 3]
x depois:  [-100    2    3]


In [ ]:
#caso queira q nao seja alterado
x = np.array([1,2,3])
print("x antes: ", x)
y = x[:2].copy() # use o copy
y[0] = -100 #alterao do valor y altera o valor de x
print("x depois: ", x)
print("y : ", y)

x antes:  [1 2 3]
x depois:  [1 2 3]
y :  [-100    2]
